/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import entity.Phim;
import javax.swing.ImageIcon;
import until.EventPhim;
import until.XImage;

/**
 *
 * @author quoct
 */
public class movie_item extends javax.swing.JPanel {

    private Phim p;
    private int index;
    EventPhim ev;

    public int getIndex() {
        return index;
    }

    public void setIndex(int index) {
        this.index = index;
    }

    public Phim getP() {
        return p;
    }

    public void setP(Phim p) {
        this.p = p;
    }

    /**
     * Creates new form movie_item
     */
    public movie_item() {
        initComponents();
    }

    public void display(EventPhim ep) {
        lblAnh.setIcon(XImage.resizeImg(new ImageIcon(getClass().getResource("/images/" + p.getHinh())), 284, 180));
        lblTenPhim.setText(p.getTenPhim());
        lblTheLoai.setText(p.getTheLoai());
        lblThoiLuong.setText(p.getThoiLuong() + "");
        ev = ep;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new ui.PanelRound();
        lblAnh = new ui.LabelRound();
        btnXepLich = new javax.swing.JButton();
        lblTenPhim = new javax.swing.JLabel();
        lblTheLoai = new ui.LabelRound();
        lblThoiLuong = new ui.LabelRound();

        setBackground(new java.awt.Color(51, 51, 51));
        setOpaque(false);

        panelRound1.setBackground(new java.awt.Color(51, 51, 51));
        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setRoundTopLeft(20);
        panelRound1.setRoundTopRight(20);
        panelRound1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlClicked(evt);
            }
        });

        lblAnh.setBackground(new java.awt.Color(0, 0, 0));
        lblAnh.setRoundBottomLeft(20);
        lblAnh.setRoundBottomRight(20);
        lblAnh.setRoundTopLeft(20);
        lblAnh.setRoundTopRight(20);

        btnXepLich.setBackground(new java.awt.Color(102, 102, 102));
        btnXepLich.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        btnXepLich.setForeground(new java.awt.Color(255, 255, 255));
        btnXepLich.setText("Xếp lịch chiếu");

        lblTenPhim.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        lblTenPhim.setForeground(new java.awt.Color(255, 255, 255));
        lblTenPhim.setText("Black Adam");

        lblTheLoai.setBackground(new java.awt.Color(0, 153, 0));
        lblTheLoai.setForeground(new java.awt.Color(255, 255, 255));
        lblTheLoai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTheLoai.setText("Thể loại");
        lblTheLoai.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblTheLoai.setRoundBottomLeft(10);
        lblTheLoai.setRoundBottomRight(10);
        lblTheLoai.setRoundTopLeft(10);
        lblTheLoai.setRoundTopRight(10);

        lblThoiLuong.setBackground(new java.awt.Color(0, 153, 0));
        lblThoiLuong.setForeground(new java.awt.Color(255, 255, 255));
        lblThoiLuong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThoiLuong.setText("Thời lượng");
        lblThoiLuong.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        lblThoiLuong.setRoundBottomLeft(10);
        lblThoiLuong.setRoundBottomRight(10);
        lblThoiLuong.setRoundTopLeft(10);
        lblThoiLuong.setRoundTopRight(10);

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXepLich, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addComponent(lblTheLoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblThoiLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTenPhim, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTenPhim, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTheLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblThoiLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXepLich, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void pnlClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlClicked
        System.out.println(index);
        ev.detailPhim(this.index);
    }//GEN-LAST:event_pnlClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXepLich;
    private ui.LabelRound lblAnh;
    private javax.swing.JLabel lblTenPhim;
    private ui.LabelRound lblTheLoai;
    private ui.LabelRound lblThoiLuong;
    private ui.PanelRound panelRound1;
    // End of variables declaration//GEN-END:variables
}
